from main.models.file import File
from main.models.user import User
from main.models.news import News
from main.models.static_pages import StaticPage
from main.models.documens_parent import DocParent
from main.models.documents_type import DocType
from main.models.type_organ import TypeOrgan
from main.models.reestr_info_user import CategoryReestrInfoUser,ReestrInfoUser
from main.models.laws import Laws,LawsCategory
