# Generated by Django 2.1.2 on 2019-09-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='status',
            field=models.CharField(choices=[('active', 'Действующий'), ('inactive', 'Прекращен'), ('paused', 'Приостановлен'), ('extended', 'Продлен')], default='inactive', max_length=20),
        ),
    ]
