# Generated by Django 2.1.2 on 2019-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190910_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
