# Generated by Django 2.1.2 on 2019-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190910_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registries',
            name='Designation_of_the_fundamental_standard',
        ),
        migrations.AddField(
            model_name='registries',
            name='designation_of_the_fundamental_standard',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='accreditation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='accreditation_duration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='inn',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='status_date',
            field=models.DateField(null=True),
        ),
    ]
