# Generated by Django 2.1.2 on 2019-10-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_staticpage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryReestrInfoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReestrInfoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('paused', 'paused'), ('extended', 'extended')], max_length=45)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='info_reestrs', to='main.CategoryReestrInfoUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='registries',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('paused', 'paused'), ('extended', 'extended')], default='inactive', max_length=20),
        ),
    ]
