# Generated by Django 2.1.2 on 2019-10-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191011_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='main.File'),
        ),
    ]
