# Generated by Django 2.1.2 on 2019-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191023_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='registries',
            name='accreditation_duration_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
