# Generated by Django 2.1.2 on 2019-10-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191029_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='accreditation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
