# Generated by Django 2.1.2 on 2019-11-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191029_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registries',
            old_name='address',
            new_name='address_organ',
        ),
        migrations.RenameField(
            model_name='registries',
            old_name='full_name',
            new_name='full_name_supervisor',
        ),
        migrations.RenameField(
            model_name='registries',
            old_name='title',
            new_name='title_organ',
        ),
    ]
