# Generated by Django 2.1.2 on 2019-11-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191107_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='registries',
            name='email_ao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registries',
            name='full_name_supervisor_ao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registries',
            name='phone_ao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registries',
            name='position_supervisor_ao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registries',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registries',
            name='web_site_ao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
