# Generated by Django 2.1.2 on 2019-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191107_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registries',
            old_name='full_name_supervisor_ao',
            new_name='full_name_supervisor_main',
        ),
        migrations.AlterField(
            model_name='registries',
            name='accreditation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='accreditation_duration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
