# Generated by Django 2.1.2 on 2019-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191118_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
