# Generated by Django 2.1.2 on 2019-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191121_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registries',
            old_name='address_applicant',
            new_name='address_yurd_lisa',
        ),
        migrations.AlterField(
            model_name='registries',
            name='email_ao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='phone_ao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
