# Generated by Django 2.1.2 on 2019-11-22 15:02

from django.db import migrations, models
import main.models.registries


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191121_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registries',
            name='file',
        ),
        migrations.AddField(
            model_name='registries',
            name='file_oblast',
            field=models.FileField(blank=True, null=True, upload_to=main.models.registries.upload_name),
        ),
    ]
