# Generated by Django 2.1.2 on 2019-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20191122_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registries',
            name='form_ownership',
        ),
        migrations.RemoveField(
            model_name='registries',
            name='full_name_supervisor_main',
        ),
        migrations.RemoveField(
            model_name='registries',
            name='position_supervisor_ao',
        ),
        migrations.RemoveField(
            model_name='registries',
            name='position_supervisor_legal',
        ),
        migrations.RemoveField(
            model_name='registries',
            name='web_site_ao',
        ),
        migrations.AddField(
            model_name='registries',
            name='is_fact_address',
            field=models.BooleanField(default=False),
        ),
    ]
