# Generated by Django 2.1.2 on 2019-11-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20191122_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistriesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('paused', 'paused'), ('extended', 'extended')], default='inactive', max_length=20)),
                ('date', models.DateField(null=True)),
                ('reestr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reestr_status', to='main.Registries')),
            ],
        ),
    ]
