# Generated by Django 2.1.2 on 2019-11-22 16:38

from django.db import migrations, models
import django.db.models.deletion
import main.models.news


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_registriesstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.news.upload_name)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.News')),
            ],
        ),
    ]
