# Generated by Django 2.1.2 on 2019-11-22 16:44

from django.db import migrations, models
import main.models.news


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_newsgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.news.upload_name),
        ),
    ]
