# Generated by Django 2.1.2 on 2019-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_news_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='main.File'),
        ),
    ]
