# Generated by Django 2.1.2 on 2019-11-22 17:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20191122_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
