# Generated by Django 2.1.2 on 2019-11-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20191122_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reestrinfouser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reestrinfouser',
            name='status',
        ),
        migrations.AddField(
            model_name='reestrinfouser',
            name='date_active',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reestrinfouser',
            name='date_inactive',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reestrinfouser',
            name='date_paused',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reestrinfouser',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='info_reestrs', to='main.CategoryReestrInfoUser'),
        ),
    ]
