# Generated by Django 2.1.2 on 2019-11-25 15:23

from django.db import migrations, models
import main.models.sliders


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20191122_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.sliders.upload_name),
        ),
    ]
