# Generated by Django 2.1.2 on 2019-11-25 15:24

from django.db import migrations, models
import main.models.employees


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20191125_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.employees.upload_name),
        ),
    ]
