# Generated by Django 2.1.2 on 2019-11-25 15:38

from django.db import migrations, models
import main.models.documents


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20191125_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('file', 'file'), ('link', 'link')], default='link', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.documents.upload_name),
        ),
    ]
