# Generated by Django 2.1.2 on 2019-11-26 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20191125_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='description_uz',
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
