# Generated by Django 2.1.2 on 2019-11-28 15:18

from django.db import migrations, models
import main.models.media_file


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20191126_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.media_file.upload_name)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
