# Generated by Django 2.1.2 on 2019-12-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date_by_admin',
            field=models.DateTimeField(null=True),
        ),
    ]
