# Generated by Django 2.1.2 on 2019-12-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_news_created_date_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='area',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
