# Generated by Django 2.1.2 on 2020-01-25 00:39

from django.db import migrations, models
import django.db.models.deletion
import main.models.inspection_control


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_confirmreestr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.inspection_control.upload_name)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_controls', to='main.ICCategory')),
            ],
        ),
    ]
