# Generated by Django 2.1.2 on 2020-01-27 11:30

from django.db import migrations, models
import django.db.models.deletion
import main.models.documents


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_iccategory_inspectioncontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.documents.upload_name)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_form', to='main.Document')),
            ],
        ),
    ]
