# Generated by Django 2.1.2 on 2020-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_registries_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeorgan',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeorgan',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeorgan',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeorgan',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
