# Generated by Django 2.1.2 on 2020-02-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200131_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typeorgan',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
