# Generated by Django 2.1.2 on 2020-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200201_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
