# Generated by Django 2.1.2 on 2020-02-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200204_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='iccategory',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='iccategory',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='iccategory',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncontrol',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncontrol',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncontrol',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
