# Generated by Django 2.1.2 on 2020-02-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20200204_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentform',
            options={'ordering': ['order'], 'verbose_name': 'Форма Документа ', 'verbose_name_plural': 'Форма Документа'},
        ),
        migrations.AddField(
            model_name='documentform',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
