# Generated by Django 2.1.2 on 2020-02-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20200204_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocumentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Форма Документа Категория',
                'verbose_name_plural': 'Форма Документа Категория',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='documentform',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_forms', to='main.CategoryDocumentForm'),
        ),
    ]
