# Generated by Django 2.1.2 on 2020-02-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20200204_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydocumentform',
            options={'ordering': ['order'], 'verbose_name': 'Категория Форма Документа ', 'verbose_name_plural': 'Категория Форма Документа '},
        ),
    ]
