# Generated by Django 2.1.2 on 2020-02-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20200204_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('file', 'file'), ('link', 'link'), ('form', 'form')], default='link', max_length=20),
        ),
    ]
