# Generated by Django 2.1.2 on 2020-02-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20200204_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydocumentform',
            options={'ordering': ['-order'], 'verbose_name': 'Категория Форма Документа ', 'verbose_name_plural': 'Категория Форма Документа '},
        ),
    ]
