# Generated by Django 2.1.2 on 2020-02-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200206_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.TextField()),
                ('active_date', models.DateField(null=True)),
                ('inactive_date', models.DateField(null=True)),
                ('paused_date', models.DateField(null=True)),
                ('extended_date', models.DateField(null=True)),
                ('reestr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reestr_logs', to='main.Registries')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='documentform',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_forms', to='main.CategoryDocumentForm'),
        ),
    ]
