# Generated by Django 2.1.2 on 2020-02-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200213_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerstatuslog',
            old_name='active_date',
            new_name='restore_date',
        ),
        migrations.RemoveField(
            model_name='registerstatuslog',
            name='extended_date',
        ),
    ]
