# Generated by Django 2.1.2 on 2020-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20200213_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerstatuslog',
            name='case',
        ),
        migrations.AddField(
            model_name='registerstatuslog',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registerstatuslog',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerstatuslog',
            name='paused_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerstatuslog',
            name='restore_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
