# Generated by Django 2.1.2 on 2020-02-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20200213_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetype',
            options={'verbose_name': 'Причина', 'verbose_name_plural': 'Причина'},
        ),
    ]
