# Generated by Django 2.1.2 on 2020-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20200213_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstatuslog',
            name='extended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerstatuslog',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
