# Generated by Django 2.1.2 on 2020-02-20 15:13

from django.db import migrations, models
import main.models.cooperation


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20200213_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('organ_accreditation', models.CharField(max_length=255)),
                ('name_document', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=255)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to=main.models.cooperation.upload_name)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cooperation_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to=main.models.cooperation.upload_name)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
