# Generated by Django 2.1.2 on 2020-02-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_cooperation_one_cooperation_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='registriesstatus',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reestr_status', to='main.CaseType'),
        ),
        migrations.AddField(
            model_name='registriesstatus',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
