# Generated by Django 2.1.2 on 2020-02-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20200224_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='registries',
            name='code_nd',
            field=models.ManyToManyField(related_name='registries', to='main.Code'),
        ),
    ]
