# Generated by Django 2.1.2 on 2020-03-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20200229_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='code_nd',
            field=models.ManyToManyField(blank=True, related_name='registries', to='main.Code'),
        ),
    ]
