# Generated by Django 2.1.2 on 2020-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20200304_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='case_type',
            new_name='code_type',
        ),
    ]
