# Generated by Django 2.1.2 on 2020-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20200304_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_type',
            field=models.CharField(choices=[('active', 'Возобновлено'), ('inactive', 'Прекращено'), ('paused', 'Приостановлено'), ('done', 'Подтверждено'), ('renewed', 'Переоформлено')], default='inactive', max_length=20),
        ),
    ]
