# Generated by Django 2.1.2 on 2020-03-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20200306_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code_type',
            new_name='organ_number',
        ),
    ]
