# Generated by Django 2.1.2 on 2020-03-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20200306_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='name',
            new_name='cod_tnved',
        ),
    ]
