# Generated by Django 2.1.2 on 2020-03-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20200306_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='registries',
            name='itt_cd',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
