# Generated by Django 2.1.2 on 2020-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20200312_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='itt_cd',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
