# Generated by Django 2.1.2 on 2020-04-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20200331_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iccategory',
            options={'ordering': ['-id'], 'verbose_name': 'Инспекционный контроль Категория', 'verbose_name_plural': 'Инспекционный контроль Категория'},
        ),
    ]
