# Generated by Django 2.1.2 on 2020-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20200413_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registriesstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Возобновлено'), ('inactive', 'Прекращено'), ('paused', 'Приостановлено'), ('done', 'Подтверждено'), ('extended', 'Продлен'), ('renewed', 'Переоформлено')], default='inactive', max_length=20),
        ),
    ]
