# Generated by Django 2.1.2 on 2020-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='registries',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='registries', to='main.Directions'),
        ),
    ]
