# Generated by Django 2.1.2 on 2020-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20200507_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='oked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registries',
            name='okonx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
