# Generated by Django 2.1.2 on 2020-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20200507_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerstatuslog',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='registerstatuslog',
            name='reestr',
        ),
        migrations.RenameField(
            model_name='registries',
            old_name='okonx',
            new_name='soogu',
        ),
        migrations.AddField(
            model_name='registries',
            name='type_accredited',
            field=models.CharField(blank=True, choices=[('competence', 'Технич. компетентность'), ('competence_independence', 'Технич. компетентность и независимость')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='registries',
            name='type_ownership',
            field=models.CharField(blank=True, choices=[('public', 'государственный'), ('private', 'частный')], max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='RegisterStatusLog',
        ),
    ]
