# Generated by Django 2.1.2 on 2020-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20200519_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registriesstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Возобновлено'), ('inactive', 'Прекращено'), ('paused', 'Приостановлено'), ('done', 'Подтверждено'), ('extended', 'Продлен'), ('renewed', 'Переоформлено'), ('OA_REDUCTION', 'Сокращение ОА')], default='inactive', max_length=20),
        ),
    ]
