# Generated by Django 2.1.2 on 2020-06-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20200529_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registries',
            options={'ordering': ['-id'], 'verbose_name': 'Государственный реестр аккредитованных ООС и МС', 'verbose_name_plural': 'Государственный реестр аккредитованных ООС и МС'},
        ),
    ]
