# Generated by Django 2.1.2 on 2020-06-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20200611_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctype',
            options={'ordering': ['-order'], 'verbose_name': 'Тип Документа', 'verbose_name_plural': 'Типы Документов'},
        ),
    ]
