# Generated by Django 2.1.2 on 2020-06-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20200611_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-id'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
