# Generated by Django 2.1.2 on 2020-06-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_auto_20200623_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsgallery',
            name='news',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.DeleteModel(
            name='NewsGallery',
        ),
    ]
