# Generated by Django 2.1.2 on 2020-06-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20200626_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncontrol',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
