# Generated by Django 2.1.2 on 2020-06-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_inspectioncontrol_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='laws',
            name='category',
        ),
        migrations.RemoveField(
            model_name='media',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Laws',
        ),
        migrations.DeleteModel(
            name='LawsCategory',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
