# Generated by Django 2.1.2 on 2020-06-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20200626_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation_one',
            name='image_main',
        ),
    ]
