# Generated by Django 2.1.2 on 2020-06-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_remove_cooperation_one_image_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation_two',
            name='image_main',
        ),
    ]
