# Generated by Django 2.1.2 on 2020-06-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_remove_cooperation_two_image_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooperation_one',
        ),
        migrations.DeleteModel(
            name='Cooperation_two',
        ),
    ]
