# Generated by Django 2.1.2 on 2020-06-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_auto_20200626_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
