# Generated by Django 2.1.2 on 2020-07-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_delete_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydocumentform',
            options={'ordering': ['order'], 'verbose_name': 'Категория Форма Документа ', 'verbose_name_plural': 'Категория Форма Документа '},
        ),
    ]
