# Generated by Django 2.1.2 on 2020-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_auto_20200706_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydocumentform',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
