# Generated by Django 2.1.2 on 2020-07-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_auto_20200707_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmreestr',
            old_name='web_site',
            new_name='address',
        ),
    ]
