# Generated by Django 2.1.2 on 2020-08-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20200730_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmreestr',
            name='email',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='full_name_supervisor_ao',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='podpisal',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='region',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='status',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='text',
        ),
        migrations.RemoveField(
            model_name='confirmreestr',
            name='type_organ',
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='reissue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='validity_date',
            field=models.DateField(null=True),
        ),
    ]
