# Generated by Django 2.1.2 on 2020-08-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_auto_20200803_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmreestr',
            name='accreditation_duration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='email_ao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='full_name_supervisor_ao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='inn',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='is_fact_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='phone_ao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='status',
            field=models.CharField(choices=[('active', 'Действующий'), ('inactive', 'Прекращен'), ('paused', 'Приостановлен'), ('extended', 'Продлен'), ('temporarily_resumed', 'Временно возобновлен')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='status_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
