# Generated by Django 2.1.2 on 2020-08-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_auto_20200809_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmreestr',
            name='designation_of_the_fundamental_standard',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='directions',
            field=models.ManyToManyField(blank=True, to='main.Directions'),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='oked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Region'),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='soogu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='type_organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.TypeOrgan'),
        ),
        migrations.AddField(
            model_name='confirmreestr',
            name='type_ownership',
            field=models.CharField(blank=True, choices=[('public', 'государственный'), ('private', 'частный')], max_length=45, null=True),
        ),
    ]
