# Generated by Django 2.1.2 on 2020-08-12 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_auto_20200812_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmreestr',
            name='area',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
