# Generated by Django 2.1.2 on 2020-08-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_auto_20200813_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='itt_cd',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
