# Generated by Django 2.1.2 on 2020-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_auto_20200819_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmreestr',
            name='is_reissue_date',
            field=models.BooleanField(default=True),
        ),
    ]
