# Generated by Django 2.1.2 on 2020-08-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_confirmreestr_is_reissue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmReestrStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Возобновлено'), ('inactive', 'Прекращено'), ('paused', 'Приостановлено'), ('done', 'Подтверждено'), ('extended', 'Продлен'), ('renewed', 'Переоформлено'), ('OA_REDUCTION', 'Сокращение ОА')], default='inactive', max_length=20)),
                ('date', models.DateField(null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('case_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CaseType')),
                ('reestr_confirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ConfirmReestr')),
            ],
        ),
    ]
