# Generated by Django 2.1.2 on 2020-08-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_confirmreestrstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedReestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title_organ', models.CharField(max_length=255, verbose_name='Наименование юр. лица')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('ministry_office', models.CharField(max_length=255, verbose_name='Вазирлик, идора')),
                ('name_of_the_conformity_assessment_body', models.CharField(max_length=255, verbose_name='Мувофиқликни баҳолаш органи номи')),
                ('field_of_activity', models.CharField(max_length=255, verbose_name='Фаолият соҳаси')),
                ('the_type_document_issued', models.CharField(max_length=255, verbose_name='Мувофиқликни тасдиқлаш учун расмийлаштирадиган ҳужжат тури')),
                ('authorized_document', models.CharField(max_length=255, verbose_name='Ваколат берилган хуқуқий ҳужжат')),
                ('type', models.CharField(choices=[('accreditation', 'аккредитация'), ('ok', 'одобрение')], max_length=255, verbose_name='Вид оценки')),
                ('mandatory_document', models.CharField(max_length=255, verbose_name='Мажбурийлиги белгиланган ҳуқуқий ҳужжат')),
            ],
            options={
                'verbose_name': 'Реестр уполномоченных',
                'verbose_name_plural': 'Реестр уполномоченных',
            },
        ),
    ]
