# Generated by Django 2.1.2 on 2020-08-31 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_authorizedreestr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedreestr',
            name='inn',
        ),
        migrations.AddField(
            model_name='authorizedreestr',
            name='confirm_reestr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ConfirmReestr', verbose_name=' Реестр одобренных лабораторий'),
        ),
        migrations.AddField(
            model_name='authorizedreestr',
            name='reestr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Registries', verbose_name=' Государственный реестр'),
        ),
    ]
